/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Cube049: THREE.Mesh;
    Cube049_1: THREE.Mesh;
    Cube090_1: THREE.Mesh;
    Cube090_2: THREE.Mesh;
    Cube083: THREE.Mesh;
    Cube090: THREE.Mesh;
    Cylinder023: THREE.Mesh;
    Cylinder023_1: THREE.Mesh;
    Object001: THREE.Mesh;
    Object004: THREE.Mesh;
    Plane014_1: THREE.Mesh;
    Plane014_2: THREE.Mesh;
    Plane003: THREE.Mesh;
    Plane004: THREE.Mesh;
    Plane017: THREE.Mesh;
    Plane017_1: THREE.Mesh;
    Plane006: THREE.Mesh;
    Plane007: THREE.Mesh;
    Plane008: THREE.Mesh;
    Plane009: THREE.Mesh;
    Plane010: THREE.Mesh;
    Plane011: THREE.Mesh;
    Plane012: THREE.Mesh;
    Plane013: THREE.Mesh;
    Plane014: THREE.Mesh;
  };
  materials: {
    ["black skin.001"]: THREE.MeshStandardMaterial;
    ["outline.001"]: THREE.MeshStandardMaterial;
    ["black plastic.001"]: THREE.MeshStandardMaterial;
    ["metal.003"]: THREE.MeshStandardMaterial;
    ["Material.015"]: THREE.MeshStandardMaterial;
    ["Material.016"]: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "assets/models/gamingchair_top.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group
        position={[0.008, -0.26, 0.602]}
        rotation={[-Math.PI, 0.079, -Math.PI]}
        scale={[0.154, 0.202, 0.255]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube049.geometry}
          material={materials["black skin.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube049_1.geometry}
          material={materials["outline.001"]}
        />
      </group>
      <group
        position={[-0.169, -0.427, 0.697]}
        rotation={[-3.022, 0.028, 2.732]}
        scale={0.255}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube090_1.geometry}
          material={materials["black skin.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube090_2.geometry}
          material={materials["outline.001"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube083.geometry}
        material={materials["black skin.001"]}
        position={[0.002, -0.215, 0.776]}
        rotation={[-2.933, 0.078, 3.125]}
        scale={[0.119, 0.115, 0.093]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube090.geometry}
        material={materials["black plastic.001"]}
        position={[0.141, -0.495, 0.584]}
        rotation={[0, 0.372, 0]}
        scale={[0.36, 0.412, 0.36]}
      />
      <group
        position={[-0.228, -0.446, 0.479]}
        rotation={[-Math.PI, 0.079, -Math.PI]}
        scale={[0.012, 0.006, 0.017]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder023.geometry}
          material={materials["black skin.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder023_1.geometry}
          material={materials["metal.003"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object001.geometry}
        material={materials["black plastic.001"]}
        position={[0.023, -0.51, 0.469]}
        rotation={[0.013, -0.079, 0.001]}
        scale={[1.063, 0.907, 1.004]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object004.geometry}
        material={materials["black plastic.001"]}
        position={[0.018, -0.473, 0.53]}
        rotation={[0, -0.079, 0]}
        scale={[1.637, 1.063, 1.063]}
      />
      <group
        position={[-0.004, -0.011, 0.824]}
        rotation={[1.536, -0.003, -3.062]}
        scale={[0.132, 0.143, 0.096]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014_1.geometry}
          material={materials["black skin.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014_2.geometry}
          material={materials["outline.001"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane003.geometry}
        material={materials["black skin.001"]}
        position={[-0.073, 0.136, 0.862]}
        rotation={[1.616, 0.004, -3.062]}
        scale={[0.038, 0.034, 0.038]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane004.geometry}
        material={materials["Material.015"]}
        position={[-0.006, 0.097, 0.835]}
        rotation={[1.76, 0.015, -3.064]}
        scale={[0.118, 0.087, 0.079]}
      />
      <group
        position={[-0.227, -0.202, 0.462]}
        rotation={[-Math.PI, 0.079, -Math.PI]}
        scale={[0.169, 0.255, 0.266]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane017.geometry}
          material={materials["black skin.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane017_1.geometry}
          material={materials["outline.001"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane006.geometry}
        material={materials["Material.016"]}
        position={[-0.195, -0.43, 0.744]}
        rotation={[-3.02, -0.098, 1.604]}
        scale={0.013}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane007.geometry}
        material={materials["Material.016"]}
        position={[-0.191, -0.43, 0.744]}
        rotation={[-3.024, -0.101, 1.583]}
        scale={0.013}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane008.geometry}
        material={materials["Material.016"]}
        position={[-0.191, -0.43, 0.744]}
        rotation={[-3.024, -0.101, 1.583]}
        scale={0.013}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane009.geometry}
        material={materials["Material.016"]}
        position={[-0.201, -0.43, 0.745]}
        rotation={[-3.024, -0.101, 1.583]}
        scale={0.013}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane010.geometry}
        material={materials["Material.016"]}
        position={[0.183, -0.26, 0.791]}
        rotation={[-3.016, 0.004, 1.651]}
        scale={0.013}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane011.geometry}
        material={materials["Material.016"]}
        position={[-0.201, -0.43, 0.745]}
        rotation={[-3.024, -0.101, 1.583]}
        scale={0.013}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012.geometry}
        material={materials["outline.001"]}
        position={[-0.071, -0.201, 0.715]}
        rotation={[1.847, 0.022, -3.065]}
        scale={[0.019, 0.079, 0.079]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane013.geometry}
        material={materials["black skin.001"]}
        position={[-0.01, 0.099, 0.886]}
        rotation={[1.64, 0.005, -3.062]}
        scale={0.008}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane014.geometry}
        material={materials["outline.001"]}
        position={[-0.006, 0.097, 0.835]}
        rotation={[1.76, 0.015, -3.064]}
        scale={[0.118, 0.087, 0.08]}
      />
    </group>
  );
}

useGLTF.preload("assets/models/gamingchair_top.glb");
